import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router'
import { setupGuards } from './guards'

const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/auth/Login.vue'),
    meta: { title: '登录', public: true },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/auth/Register.vue'),
    meta: { title: '注册', public: true },
  },
  {
    path: '/',
    component: () => import('@/components/layout/AppLayout.vue'),
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/dashboard/Dashboard.vue'),
        meta: { title: '工作台' },
      },
      {
        path: 'projects',
        name: 'ProjectList',
        component: () => import('@/views/project/ProjectList.vue'),
        meta: { title: '项目管理', permissions: ['project:view'] },
      },
      {
        path: 'projects/:id',
        name: 'ProjectDetail',
        component: () => import('@/views/project/ProjectDetail.vue'),
        meta: { title: '项目详情', permissions: ['project:view'] },
      },
      {
        path: 'reviews',
        name: 'ReviewTaskList',
        component: () => import('@/views/review/ReviewTaskList.vue'),
        meta: { title: '审查记录', permissions: ['review:view'] },
      },
      {
        path: 'reviews/:id',
        name: 'ReviewTaskDetail',
        component: () => import('@/views/review/ReviewTaskDetail.vue'),
        meta: { title: '审查详情', permissions: ['review:view'] },
      },
      {
        path: 'reviews/start',
        name: 'ReviewStart',
        component: () => import('@/views/review/ReviewStart.vue'),
        meta: { title: '发起审查', permissions: ['review:start'] },
      },
      {
        path: 'pentests',
        name: 'PentestList',
        component: () => import('@/views/pentest/PentestList.vue'),
        meta: { title: '渗透测试', permissions: ['pentest:view'] },
      },
      {
        path: 'pentests/start',
        name: 'PentestStart',
        component: () => import('@/views/pentest/PentestStart.vue'),
        meta: { title: '发起渗透测试', permissions: ['pentest:start'] },
      },
      {
        path: 'pentests/:publicId',
        name: 'PentestDetail',
        component: () => import('@/views/pentest/PentestDetail.vue'),
        meta: { title: '渗透测试详情', permissions: ['pentest:view'] },
      },
      {
        path: 'rules',
        name: 'RuleConfig',
        redirect: { path: '/security', query: { section: 'rules' } },
        meta: { title: '审查规则', permissions: ['rule:view'] },
      },
      {
        path: 'security',
        name: 'SecurityCenter',
        component: () => import('@/views/security/SecurityReviewCenter.vue'),
        meta: { title: '安全与审查规则', permissions: ['security:view', 'rule:view'] },
      },
      {
        path: 'reports',
        name: 'ReportList',
        component: () => import('@/views/report/ReportList.vue'),
        meta: { title: '审查报告', permissions: ['report:view'] },
      },
      {
        path: 'reports/:id',
        name: 'ReportDetail',
        component: () => import('@/views/report/ReportDetail.vue'),
        meta: { title: '报告详情', permissions: ['report:view'] },
      },
      {
        path: 'report/templates',
        name: 'ReportTemplateManage',
        component: () => import('@/views/report/ReportTemplateManage.vue'),
        meta: { title: '报告模板管理', permissions: ['report:template_manage'] },
      },
      {
        path: 'code/:projectId',
        name: 'CodeFileList',
        component: () => import('@/views/code/CodeFileList.vue'),
        meta: { title: '代码文件', permissions: ['file:view'] },
        props: (route) => ({ projectId: Number(route.params.projectId) }),
      },
      {
        path: 'code/:projectId/file/:fileId',
        name: 'CodeEditor',
        component: () => import('@/views/code/CodeEditor.vue'),
        meta: { title: '编辑器', permissions: ['file:view'] },
      },
      {
        path: 'code/:projectId/file/:fileId/versions',
        name: 'VersionHistory',
        component: () => import('@/views/code/VersionHistory.vue'),
        meta: { title: '版本历史', permissions: ['file:view'] },
      },
      {
        path: 'code',
        name: 'CodeHub',
        component: () => import('@/views/code/CodeHub.vue'),
        meta: { title: '代码中心', permissions: ['file:view'] },
      },
      {
        path: 'issues',
        name: 'IssueHub',
        component: () => import('@/views/issue/IssueHub.vue'),
        meta: { title: '问题追踪', permissions: ['issue:view'] },
      },
      {
        path: 'agents',
        name: 'AgentCenter',
        component: () => import('@/views/agent/AgentWorkspace.vue'),
        meta: { title: 'Agent 工作台', permissions: ['agent:view', 'agent_asset:create'] },
      },
      {
        path: 'sandboxes',
        name: 'SandboxWorkstation',
        component: () => import('@/views/sandbox/SandboxWorkstation.vue'),
        meta: { title: '代码沙箱' },
      },
      {
        path: 'agent-studio',
        name: 'AgentStudio',
        redirect: { path: '/agents', query: { section: 'studio' } },
        meta: { title: 'Agent 工坊', roles: ['reviewer', 'admin'], permissions: ['agent_asset:create'] },
      },
      {
        path: 'forum',
        name: 'ForumList',
        component: () => import('@/views/forum/ForumList.vue'),
        meta: { title: '开发者论坛' },
      },
      {
        path: 'forum/new',
        name: 'ForumPostCreate',
        component: () => import('@/views/forum/ForumPostEdit.vue'),
        meta: { title: '发布新帖' },
      },
      {
        path: 'forum/:id',
        name: 'ForumPostDetail',
        component: () => import('@/views/forum/ForumPostDetail.vue'),
        meta: { title: '帖子详情' },
      },
      {
        path: 'forum/:id/edit',
        name: 'ForumPostEdit',
        component: () => import('@/views/forum/ForumPostEdit.vue'),
        meta: { title: '编辑帖子' },
      },
      {
        path: 'knowledge',
        name: 'KnowledgeBase',
        component: () => import('@/views/knowledge/KnowledgeBase.vue'),
        meta: { title: '个人知识库' },
      },
      {
        path: 'support',
        name: 'SupportCenter',
        component: () => import('@/views/support/SupportCenter.vue'),
        meta: { title: '支持中心' },
      },
      {
        path: 'support/maintenance',
        name: 'MaintenanceCenter',
        redirect: { path: '/support', query: { section: 'maintenance' } },
        meta: { title: '申请维修' },
      },
      {
        path: 'support/feedback',
        name: 'FeedbackCenter',
        redirect: { path: '/support', query: { section: 'feedback' } },
        meta: { title: '意见反馈' },
      },
      {
        path: 'profile',
        name: 'ProfileCenter',
        component: () => import('@/views/profile/ProfileCenter.vue'),
        meta: { title: '个人中心' },
      },
      {
        path: 'profile/personalization',
        name: 'PersonalizationCenter',
        component: () => import('@/views/profile/PersonalizationCenter.vue'),
        meta: { title: '个性化画像' },
      },
      {
        path: 'profile/password',
        name: 'ChangePassword',
        component: () => import('@/views/profile/ChangePassword.vue'),
        meta: { title: '修改密码' },
      },
      {
        path: 'profile/api-config',
        name: 'ApiConfig',
        component: () => import('@/views/profile/ApiConfig.vue'),
        meta: { title: 'API 配置' },
      },
    ],
  },
  {
    path: '/admin',
    component: () => import('@/components/admin/AdminLayout.vue'),
    meta: { role: 'admin', roles: ['admin'] },
    children: [
      {
        path: '',
        redirect: { path: '/admin/operations', query: { section: 'overview' } },
      },
      {
        path: 'governance',
        name: 'AdminGovernanceCenter',
        component: () => import('@/views/admin/AdminUnifiedCenter.vue'),
        meta: { title: 'Agent 治理中心', role: 'admin', roles: ['admin'], unifiedDomain: 'agents' },
      },
      {
        path: 'operations',
        name: 'AdminOperationsCenter',
        component: () => import('@/views/admin/AdminUnifiedCenter.vue'),
        meta: { title: '运行与审计中心', role: 'admin', roles: ['admin'], unifiedDomain: 'operations' },
      },
      {
        path: 'access',
        name: 'AdminAccessCenter',
        component: () => import('@/views/admin/AdminUnifiedCenter.vue'),
        meta: { title: '用户与权限中心', role: 'admin', roles: ['admin'], unifiedDomain: 'access' },
      },
      {
        path: 'platform',
        name: 'AdminPlatformCenter',
        component: () => import('@/views/admin/AdminUnifiedCenter.vue'),
        meta: { title: '平台配置中心', role: 'admin', roles: ['admin'], unifiedDomain: 'platform' },
      },
      {
        path: 'overview',
        name: 'AdminOverview',
        redirect: { path: '/admin/operations', query: { section: 'overview' } },
        meta: { title: '总览大屏', role: 'admin', roles: ['admin'] },
      },
      {
        path: 'agents',
        name: 'AgentGovernance',
        redirect: { path: '/admin/governance', query: { section: 'agents' } },
        meta: { title: 'Agent 管理', role: 'admin' },
      },
      {
        path: 'approvals',
        name: 'ApprovalCenter',
        redirect: { path: '/admin/governance', query: { section: 'approvals' } },
        meta: { title: '审批中心', role: 'admin' },
      },
      {
        path: 'agent-releases',
        name: 'AgentReleaseAdmin',
        redirect: { path: '/admin/governance', query: { section: 'releases' } },
        meta: { title: 'Agent 发布审批', role: 'admin', permissions: ['agent_asset:approve'] },
      },
      {
        path: 'beta-codes',
        name: 'BetaCodeAdmin',
        redirect: { path: '/admin/platform', query: { section: 'beta-codes' } },
        meta: { title: '内测码管理', role: 'admin' },
      },
      {
        path: 'policies',
        name: 'PolicyCenter',
        redirect: { path: '/admin/operations', query: { section: 'policies' } },
        meta: { title: '策略中心', role: 'admin' },
      },
      {
        path: 'tools',
        name: 'ToolGovernance',
        redirect: { path: '/admin/operations', query: { section: 'tools' } },
        meta: { title: '工具权限', role: 'admin' },
      },
      {
        path: 'knowledge',
        name: 'KnowledgeGovernance',
        redirect: { path: '/admin/governance', query: { section: 'knowledge' } },
        meta: { title: '知识与记忆', role: 'admin' },
      },
      {
        path: 'jobs',
        name: 'JobCenter',
        redirect: { path: '/admin/operations', query: { section: 'jobs' } },
        meta: { title: '任务调度', role: 'admin' },
      },
      {
        path: 'observability',
        name: 'ObservabilityCenter',
        redirect: { path: '/admin/operations', query: { section: 'observability' } },
        meta: { title: '监控告警', role: 'admin' },
      },
      {
        path: 'rewards',
        name: 'RewardCenter',
        redirect: { path: '/admin/operations', query: { section: 'rewards' } },
        meta: { title: '奖惩趋势', role: 'admin' },
      },
      {
        path: 'rollback',
        name: 'RollbackCenter',
        redirect: { path: '/admin/operations', query: { section: 'rollback' } },
        meta: { title: '回滚中心', role: 'admin' },
      },
      {
        path: 'users',
        name: 'UserManage',
        redirect: { path: '/admin/access', query: { section: 'users' } },
        meta: { title: '用户管理', role: 'admin', roles: ['admin'], permissions: ['user:view'] },
      },
      {
        path: 'rbac/roles',
        name: 'RoleManage',
        redirect: { path: '/admin/access', query: { section: 'roles' } },
        meta: { title: '角色管理', role: 'admin', roles: ['admin'], permissions: ['role:manage'] },
      },
      {
        path: 'rbac/permissions',
        name: 'PermissionList',
        redirect: { path: '/admin/access', query: { section: 'permissions' } },
        meta: { title: '权限点列表', role: 'admin', roles: ['admin'], permissions: ['role:manage'] },
      },
      {
        path: 'rbac/users',
        name: 'UserRoleAssign',
        redirect: { path: '/admin/access', query: { section: 'users' } },
        meta: { title: '用户角色分配', role: 'admin', roles: ['admin'], permissions: ['user:view'] },
      },
      {
        path: 'ai-logs',
        name: 'AiLogList',
        redirect: { path: '/admin/operations', query: { section: 'ai-logs' } },
        meta: { title: 'Agent 调用日志', role: 'admin' },
      },
      {
        path: 'report-templates',
        name: 'AdminReportTemplateManage',
        redirect: { path: '/admin/platform', query: { section: 'report-templates' } },
        meta: { title: '报告模板管理', role: 'admin', permissions: ['report:template_manage'] },
      },
      {
        path: 'audit',
        name: 'SystemAudit',
        redirect: { path: '/admin/operations', query: { section: 'audit' } },
        meta: { title: '系统操作审计', role: 'admin', permissions: ['audit:view'] },
      },
      {
        path: 'evolution',
        name: 'EvolutionCenter',
        redirect: { path: '/admin/governance', query: { section: 'evolution' } },
        meta: { title: 'Agent 自进化', role: 'admin' },
      },
      {
        path: 'skills',
        name: 'SkillManager',
        redirect: { path: '/admin/governance', query: { section: 'skills' } },
        meta: { title: 'Skill 管理', role: 'admin' },
      },
      {
        path: 'embedding',
        name: 'EmbeddingConfig',
        redirect: { path: '/admin/platform', query: { section: 'embedding' } },
        meta: { title: 'RAG 嵌入配置', role: 'admin', superAdmin: true },
      },
      {
        path: 'mcp-workers',
        name: 'McpWorkerGovernance',
        redirect: { path: '/admin/platform', query: { section: 'mcp-workers' } },
        meta: { title: 'MCP 与沙箱节点', role: 'admin', roles: ['admin'], superAdmin: true },
      },
      {
        path: 'llm',
        name: 'LlmConfig',
        redirect: { path: '/admin/platform', query: { section: 'llm' } },
        meta: { title: '大模型配置', role: 'admin', superAdmin: true },
      },
    ],
  },
  {
    path: '/403',
    name: 'Forbidden',
    component: () => import('@/views/error/Forbidden.vue'),
    meta: { title: '无权限', public: true },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/views/error/NotFound.vue'),
    meta: { title: '页面不存在', public: true },
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
})

setupGuards(router)

export default router
