"""Agent 治理观测服务。"""

import json
import math
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import func, or_
from sqlalchemy.orm import Session

from app.core.exceptions import NotFoundError
from app.models.agent_governance import (
    AgentAlert,
    AgentJobRun,
    AgentMetricSnapshot,
    AgentRewardEvent,
    ApprovalItem,
    PolicyDecisionLog,
    ToolCallLog,
)

_SECURITY_MONITOR_CATEGORIES = {
    "attack",
    "backup",
    "brute_force",
    "db_threat",
    "integration",
    "login",
    "optimization",
    "proxy_abuse",
    "scanner",
}
_ASCII_WHITESPACE = " \t\n\r\v\f"


def _sql_compact_alert_value(value):
    """跨 SQLite/MySQL 删除告警字段中的 ASCII 空白，避免 SQL/Python 分类不一致。"""
    for char in _ASCII_WHITESPACE:
        value = func.replace(value, char, "")
    return value


def _compact_alert_value(value: Optional[str]) -> str:
    """与 SQL 分类保持一致：小写并删除 ASCII 空白字符。"""
    return "".join(char for char in (value or "").lower() if char not in _ASCII_WHITESPACE)


def security_monitor_alert_clause():
    """返回覆盖当前及未标记来源的历史安全告警分类条件。"""
    source = _sql_compact_alert_value(func.lower(func.coalesce(AgentAlert.source, "")))
    alert_type = _sql_compact_alert_value(func.lower(func.coalesce(AgentAlert.alert_type, "")))
    category = _sql_compact_alert_value(func.lower(func.coalesce(AgentAlert.category, "")))
    return or_(
        source == "security_monitor",
        alert_type.like("security.%"),
        (source == "") & category.in_(_SECURITY_MONITOR_CATEGORIES),
    )


def is_security_monitor_alert(alert: AgentAlert) -> bool:
    """按可信安全告警类型/类别识别记录，不依赖可空的迁移来源列。"""
    alert_type = _compact_alert_value(alert.alert_type)
    category = _compact_alert_value(alert.category)
    source = _compact_alert_value(alert.source)
    return source == "security_monitor" or alert_type.startswith("security.") or (
        not source and category in _SECURITY_MONITOR_CATEGORIES
    )


def _exclude_security_monitor_alerts(query):
    return query.filter(~security_monitor_alert_clause())


def create_alert(
    db: Session,
    *,
    alert_type: str,
    severity: str,
    title: str,
    detail: Optional[dict] = None,
    category: Optional[str] = None,
    source: Optional[str] = None,
    user_id: Optional[int] = None,
    read_at: Optional[datetime] = None,
    fingerprint: Optional[str] = None,
) -> AgentAlert:
    """Persist a governance alert generated by a real runtime event.

    Args:
        db: 数据库会话。
        alert_type: 告警类型（如 ops_health / security.login）。
        severity: 严重度（info/warning/high/critical）。
        title: 告警标题。
        detail: 详情 JSON。
        category: 安全监控告警类别（可选）。
        source: 告警来源（如 security_monitor，可选）。
        user_id: 弹窗目标管理员 ID（可选）。
        read_at: 已读时间（可选，默认未读）。
        fingerprint: 去重指纹（可选）。

    Returns:
        AgentAlert: 已落库的告警。
    """
    row = AgentAlert(
        alert_type=alert_type,
        severity=severity,
        status="open",
        title=title[:200],
        detail_json=json.dumps(detail or {}, ensure_ascii=False),
        category=category,
        source=source,
        user_id=user_id,
        read_at=read_at,
        fingerprint=fingerprint,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def snapshot(
    db: Session,
    metric_key: str,
    metric_value: float,
    dimension: Optional[dict] = None,
) -> AgentMetricSnapshot:
    """Persist one measured governance metric for trend analysis."""
    now = datetime.now(timezone.utc)
    row = AgentMetricSnapshot(
        metric_key=metric_key,
        metric_value=metric_value,
        dimension_json=json.dumps(dimension or {}, ensure_ascii=False),
        window_start=now,
        window_end=now,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def overview(db: Session) -> dict:
    """聚合治理观测指标。

    Args:
        db: 数据库会话。

    Returns:
        dict: 观测指标摘要。
    """
    tool_status = db.query(ToolCallLog.status, func.count(ToolCallLog.id)).group_by(ToolCallLog.status).all()
    approval_status = db.query(ApprovalItem.status, func.count(ApprovalItem.id)).group_by(ApprovalItem.status).all()
    risk_distribution = (
        db.query(PolicyDecisionLog.risk_level, func.count(PolicyDecisionLog.id))
        .group_by(PolicyDecisionLog.risk_level)
        .all()
    )
    return {
        "tool_status": [{"status": status or "unknown", "count": count} for status, count in tool_status],
        "approval_status": [{"status": status or "unknown", "count": count} for status, count in approval_status],
        "risk_distribution": [{"risk_level": risk or "unknown", "count": count} for risk, count in risk_distribution],
        "open_alerts": db.query(AgentAlert).filter(AgentAlert.status == "open").count(),
        "job_runs": db.query(AgentJobRun).count(),
        "reward_score_total": float(db.query(func.coalesce(func.sum(AgentRewardEvent.score), 0.0)).scalar() or 0.0),
    }


def list_alerts(
    db: Session,
    status: str = "open",
    limit: int = 100,
    *,
    include_security_monitor: bool = True,
) -> list[AgentAlert]:
    """查询治理告警。

    Args:
        db: 数据库会话。
        status: 告警状态。
        limit: 最大返回条数。

    Returns:
        list[AgentAlert]: 告警列表。
    """
    q = db.query(AgentAlert)
    if status:
        q = q.filter(AgentAlert.status == status)
    if not include_security_monitor:
        q = _exclude_security_monitor_alerts(q)
    return q.order_by(AgentAlert.id.desc()).limit(limit).all()


def list_alerts_page(
    db: Session,
    status: str = "open",
    page: int = 1,
    page_size: int = 20,
    *,
    include_security_monitor: bool = True,
) -> dict:
    """分页查询治理告警，并返回完整匹配总数。"""
    q = db.query(AgentAlert)
    if status:
        q = q.filter(AgentAlert.status == status)
    if not include_security_monitor:
        q = _exclude_security_monitor_alerts(q)
    total = q.count()
    items = q.order_by(AgentAlert.id.desc()).offset((page - 1) * page_size).limit(page_size).all()
    return {
        "items": items,
        "total": total,
        "page": page,
        "page_size": page_size,
        "pages": math.ceil(total / page_size) if total else 0,
    }


def resolve_alert(
    db: Session,
    alert_id: int,
    admin_id: int,
    note: str = "",
    admin_name: str = "",
) -> AgentAlert:
    """关闭治理告警。

    Args:
        db: 数据库会话。
        alert_id: 告警 ID。
        admin_id: 处理人 ID。
        note: 处理说明。

    Returns:
        AgentAlert: 关闭后的告警。

    Raises:
        NotFoundError: 告警不存在。
    """
    alert = db.get(AgentAlert, alert_id)
    if not alert:
        raise NotFoundError("治理告警不存在", code=40400)
    alert.status = "resolved"
    alert.resolved_by = admin_id
    alert.resolved_at = datetime.now(timezone.utc)
    try:
        original = json.loads(alert.detail_json or "{}")
    except (json.JSONDecodeError, TypeError):
        original = {"legacy_detail": alert.detail_json}
    if not isinstance(original, dict):
        original = {"original_detail": original}
    resolution = {
        "note": str(note or "")[:2000],
        "resolved_by": int(admin_id),
        "resolved_by_name": str(admin_name or "")[:80] or None,
        "resolved_at": datetime.now(timezone.utc).isoformat(),
    }
    history = original.get("resolutions")
    history = history if isinstance(history, list) else []
    original["resolutions"] = [*history[-19:], resolution]
    original["resolution"] = resolution
    alert.detail_json = json.dumps(original, ensure_ascii=False, default=str)
    db.commit()
    db.refresh(alert)
    return alert
