rule Prism_EICAR_Test_File
{
    meta:
        description = "EICAR antivirus test signature"
        version = "2026-07-10"
        severity = "test"
    strings:
        $eicar = "EICAR-STANDARD-ANTIVIRUS-TEST-FILE" ascii
    condition:
        $eicar
}

// 合法库白名单：命中即压制同名前缀的威胁规则，防误报。
// 这些库本身含 eval/base64_decode 等高危函数但属正常实现。
rule Prism_Benign_Known_Good_Lib
{
    meta:
        description = "Whitelist for known-good libraries that legitimately contain eval/base64 (HTMLPurifier, etc.)"
        version = "2026-08-05"
        severity = "whitelist"
    strings:
        // HTMLPurifier 官方 standalone 打包文件的生成器标记
        $htmlpurifier_gen = "auto-generated by generate-includes.php" ascii
        $htmlpurifier_ns  = "HTML Purifier" ascii
        $htmlpurifier_cls = "class HTMLPurifier" ascii nocase
    condition:
        any of ($htmlpurifier*)
}

rule Prism_High_Confidence_PHP_Webshell
{
    meta:
        description = "High confidence PHP eval plus base64 decode webshell pattern"
        version = "2026-08-05"
        severity = "high"
    strings:
        $php = "<?php" ascii nocase
        $eval = /eval\s*\(/ ascii nocase
        $decode = /base64_decode\s*\(/ ascii nocase
    condition:
        $php and $eval and $decode and not Prism_Benign_Known_Good_Lib
}
